<%@ Page Language="C#" AutoEventWireup="true" CodeFile="view_add.aspx.cs" Inherits="view_add" %>

<!DOCTYPE html>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>View Posted Advertise Page</title>
    
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="styles.css" rel="stylesheet" type="text/css" />
</head>
<body>

    <form id="form1" runat="server">

<div id="main_bg">
<div id="main">
<!-- header -->
<div id="header">
	<div id="logo">
		<img src="images/logo.jpg" height="100%" width="100%" />
	</div>
 <div id="buttons">
	<a href="Default.aspx" class="but_home" title=""></a><div class="but_razd"></div>
	<a href="add_advertise.aspx" class="but" title="">Add Advertise</a>
    <a href="view_add.aspx" class="but" title="">View Advertise</a>
    <a href="logout.aspx" class="but" title="">LogOut</a>
	</div>
</div><div class="inner_copy"><div class="inner_copy">
</div></div>
<!-- / header -->
<!-- content -->
				<div class="cont_top"></div>
				<div id="content">
				<div style=" height:10px"></div>
				  <p align="center"><font size="+3" color="#993399">View Posted Advertise</font></p>
				  <p align="center">&nbsp;</p>
				  <div id="left">

					
                      <asp:GridView ID="GridView1" runat="server" Width="639px" AutoGenerateColumns="False" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" AutoGenerateDeleteButton="True" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" OnSelectedIndexChanging="GridView1_SelectedIndexChanging" OnRowCommand="GridView1_RowCommand">
                          <Columns>
                                <asp:TemplateField HeaderText="Advertise ID">
                                    <ItemTemplate>
                                        <asp:Label ID="laid" runat="server" Text='<%#Eval("aid") %>'></asp:Label>
                                    </ItemTemplate>      
                                </asp:TemplateField>   

                               <asp:TemplateField HeaderText="Advertise Category">
                                    <ItemTemplate>
                                        <asp:Label ID="ad_cat" runat="server" Text='<%#Eval("ad_cat") %>'></asp:Label>
                                    </ItemTemplate>
                                    <EditItemTemplate>
                                     
                                        <asp:TextBox id="tcat" runat="server" Text='<%#Eval("ad_cat") %>'></asp:TextBox>
                                    </EditItemTemplate> 
                                </asp:TemplateField>   

                               <asp:TemplateField HeaderText="Advertise Description">
                                    <ItemTemplate>
                                        <asp:Label ID="ad_desc" runat="server" Text='<%#Eval("ad_desc") %>'></asp:Label>
                                    </ItemTemplate>
                                    <EditItemTemplate>
                                        <asp:TextBox id="tdesc" runat="server" Text='<%#Eval("ad_desc") %>'></asp:TextBox>
                                        
                                    </EditItemTemplate> 
                                </asp:TemplateField>   

                               <asp:TemplateField HeaderText="Date">
                                    <ItemTemplate>
                                        <asp:Label ID="dat" runat="server" Text='<%#Eval("dat") %>'></asp:Label>
                                    </ItemTemplate>
                                    <EditItemTemplate>
                                        <asp:TextBox id="tdate" runat="server" Text='<%#Eval("dat") %>'></asp:TextBox>
              
                                    </EditItemTemplate> 
                                </asp:TemplateField>  
                              
                               <asp:TemplateField HeaderText="Status">
                                    <ItemTemplate>
                                        <asp:Label ID="status" runat="server" Text='<%#Eval("status") %>'></asp:Label>
                                    </ItemTemplate>
                                    <EditItemTemplate>
                                        <asp:TextBox id="tstatus" runat="server" Text='<%#Eval("status") %>'></asp:TextBox>
                                    </EditItemTemplate> 
                                </asp:TemplateField> 
                                 <asp:TemplateField HeaderText="Actions">
                                    <ItemTemplate>
                                        <asp:LinkButton ID="select_a" runat="server" OnClick="select_a_Click" PostBackUrl='<%# "~/detail_ad.aspx?aid="+ Eval("aid") %>'> select </asp:LinkButton>
                                    </ItemTemplate>       
                                </asp:TemplateField> 
                                <asp:CommandField ShowEditButton="true" />
                    
                          </Columns>
                      </asp:GridView>

					
                      <br />

					
                   </div>
<!-- / content --> 
  <div style="height:15px"></div>
<!-- bottom -->
	<div id="bottom"></div>
	<div style="clear: both;"></div>
</div>

<!-- / bottom --> 
	<div id="footer">
		<p>Welcome To Our Website</p>
		
</div>
</div>

</div>

    </form>

</body>
</html>
